import type { Job } from "@/types/job";

export const initialJobs: Job[] = [
  {
    id: "job-001",
    title: "前端开发工程师",
    company: "字节跳动",
    channel: "Boss直聘",
    location: "北京",
    salary: "25k-40k",
    url: "https://www.zhipin.com/job_detail/job-001.html",
    status: "first_interview",
    appliedAt: "2024-05-26",
    description:
      "负责增长业务的前端体验建设，参与复杂表单、数据看板和活动页工程化。",
    skills: ["React", "TypeScript", "Next.js", "性能优化"],
  },
  {
    id: "job-002",
    title: "高级前端工程师",
    company: "腾讯",
    channel: "内推",
    location: "深圳",
    salary: "28k-45k",
    url: "https://careers.tencent.com/job/job-002",
    status: "written_test",
    appliedAt: "2024-05-25",
    description:
      "负责企业协同产品前端架构升级，建设组件体系和可观测前端质量指标。",
    skills: ["React", "Webpack", "Node.js", "微前端"],
  },
  {
    id: "job-003",
    title: "前端开发工程师",
    company: "阿里巴巴",
    channel: "官网",
    location: "杭州",
    salary: "22k-38k",
    url: "https://talent.alibaba.com/job-003",
    status: "second_interview",
    appliedAt: "2024-05-24",
    description:
      "参与商家后台与数据产品建设，关注复杂交互、状态管理和跨团队协作。",
    skills: ["Vue", "TypeScript", "Sass", "E2E"],
  },
  {
    id: "job-004",
    title: "前端工程师",
    company: "美团",
    channel: "拉勾网",
    location: "北京",
    salary: "20k-35k",
    url: "https://www.lagou.com/jobs/job-004.html",
    status: "hr_interview",
    appliedAt: "2024-05-22",
    description:
      "负责本地生活营销工具和运营后台，提高投放链路的可用性与效率。",
    skills: ["React", "Zustand", "Tailwind CSS", "Chart.js"],
  },
  {
    id: "job-005",
    title: "Web 前端开发",
    company: "京东",
    channel: "招聘",
    location: "北京",
    salary: "18k-30k",
    url: "https://campus.jd.com/job-005",
    status: "applied",
    appliedAt: "2024-05-21",
    description:
      "建设供应链业务中台页面，维护基础组件和表格、搜索、审批等通用能力。",
    skills: ["Vue", "Element Plus", "Vite", "低代码"],
  },
  {
    id: "job-006",
    title: "前端开发工程师",
    company: "小米",
    channel: "内推",
    location: "北京",
    salary: "18k-32k",
    url: "https://hr.xiaomi.com/job-006",
    status: "pending",
    appliedAt: "2024-05-20",
    description:
      "负责 IoT 管理平台体验优化，推进页面性能、可维护性和组件复用。",
    skills: ["React", "TypeScript", "Ant Design", "权限系统"],
  },
  {
    id: "job-007",
    title: "前端开发工程师",
    company: "滴滴",
    channel: "Boss直聘",
    location: "北京",
    salary: "20k-34k",
    url: "https://www.zhipin.com/job_detail/job-007.html",
    status: "rejected",
    appliedAt: "2024-05-19",
    description:
      "负责出行运营后台和城市数据看板，要求有复杂业务建模与工程实践经验。",
    skills: ["React", "Redux", "可视化", "CI/CD"],
  },
  {
    id: "job-008",
    title: "前端开发工程师",
    company: "百度",
    channel: "官网",
    location: "北京",
    salary: "24k-40k",
    url: "https://talent.baidu.com/job-008",
    status: "offer",
    appliedAt: "2024-05-18",
    description:
      "参与 AI 产品控制台研发，负责模型管理、任务编排和数据分析体验。",
    skills: ["React", "TypeScript", "ECharts", "Node.js"],
  },
  {
    id: "job-009",
    title: "React 前端工程师",
    company: "快手",
    channel: "猎聘",
    location: "北京",
    salary: "23k-38k",
    url: "https://www.liepin.com/job/job-009.shtml",
    status: "first_interview",
    appliedAt: "2024-05-17",
    description:
      "负责内容创作者工具和数据分析系统，关注交互细节和前端稳定性。",
    skills: ["React", "TypeScript", "SWR", "监控"],
  },
  {
    id: "job-010",
    title: "Vue 前端工程师",
    company: "B站",
    channel: "Boss直聘",
    location: "上海",
    salary: "18k-32k",
    url: "https://www.zhipin.com/job_detail/job-010.html",
    status: "applied",
    appliedAt: "2024-05-16",
    description:
      "建设社区运营后台，优化内容审核、账号治理和配置平台体验。",
    skills: ["Vue", "Pinia", "Vite", "Vitest"],
  },
  {
    id: "job-011",
    title: "全栈前端工程师",
    company: "小红书",
    channel: "内推",
    location: "上海",
    salary: "25k-42k",
    url: "https://careers.xiaohongshu.com/job-011",
    status: "pending",
    appliedAt: "2024-05-15",
    description:
      "负责商业化增长平台，兼顾前端页面、接口聚合和工程效率建设。",
    skills: ["Next.js", "Node.js", "Prisma", "A/B Test"],
  },
  {
    id: "job-012",
    title: "前端基础架构工程师",
    company: "网易",
    channel: "官网",
    location: "广州",
    salary: "22k-36k",
    url: "https://hr.163.com/job-012",
    status: "written_test",
    appliedAt: "2024-05-14",
    description:
      "建设前端脚手架、构建工具和组件文档，推动研发流程标准化。",
    skills: ["TypeScript", "Vite", "Monorepo", "工程化"],
  },
];

export const jobChannels = Array.from(
  new Set(initialJobs.map((job) => job.channel)),
);

export const jobLocations = Array.from(
  new Set(initialJobs.map((job) => job.location)),
);
