import type {
  ProjectMatch,
  SkillCategory,
  SkillRequirement,
  TargetRole,
} from "@/types/skill-analysis";

export const skillCategories: {
  id: SkillCategory;
  label: string;
  description: string;
}[] = [
  {
    id: "core",
    label: "基础能力",
    description: "语言、浏览器、网络和工程基础",
  },
  {
    id: "framework",
    label: "框架生态",
    description: "React、Vue、Next.js 等业务开发框架",
  },
  {
    id: "engineering",
    label: "工程质量",
    description: "测试、性能、监控、可维护性和协作",
  },
  {
    id: "tooling",
    label: "构建工具",
    description: "Vite、Webpack、CI/CD、Monorepo",
  },
  {
    id: "backend",
    label: "后端协作",
    description: "Node.js、接口设计、数据库和部署",
  },
];

export const targetRoles: TargetRole[] = [
  {
    id: "frontend",
    label: "前端开发工程师",
    description: "匹配中后台、数据看板、业务平台类岗位。",
    keywords: ["React", "TypeScript", "状态管理", "性能优化"],
  },
  {
    id: "senior-frontend",
    label: "高级前端工程师",
    description: "匹配架构设计、组件体系、工程效率类岗位。",
    keywords: ["工程化", "组件库", "监控", "CI/CD"],
  },
  {
    id: "fullstack-frontend",
    label: "全栈前端工程师",
    description: "匹配 Next.js、Node.js、接口聚合和部署类岗位。",
    keywords: ["Next.js", "Node.js", "数据库", "部署"],
  },
];

export const skillRequirements: SkillRequirement[] = [
  {
    id: "react",
    name: "React",
    category: "framework",
    demand: 92,
    current: 88,
    target: 90,
    trend: "up",
    relatedJobs: ["字节跳动", "美团", "百度", "快手"],
    evidence: ["JobPilot 使用 React 19 和 App Router 组织页面", "已完成表格、弹窗、看板等交互组件"],
    recommendation: "补充 hooks 设计、组件边界和状态拆分的项目复盘。",
    learningPlan: ["整理 3 个自定义 hooks 案例", "补充复杂表单性能优化记录", "准备组件拆分取舍说明"],
    matchedProjects: ["JobPilot", "ChatFlow"],
  },
  {
    id: "typescript",
    name: "TypeScript",
    category: "core",
    demand: 88,
    current: 82,
    target: 90,
    trend: "up",
    relatedJobs: ["腾讯", "阿里巴巴", "百度", "网易"],
    evidence: ["已为岗位、面试、技能分析建立类型模型", "表单、筛选和拖拽逻辑保持类型约束"],
    recommendation: "加强泛型组件、联合类型和数据模型设计表达。",
    learningPlan: ["复盘 JobStatus 与 InterviewStage 的联合类型", "写一篇表单模型类型设计说明", "准备一道泛型工具类型题"],
    matchedProjects: ["JobPilot"],
  },
  {
    id: "nextjs",
    name: "Next.js",
    category: "framework",
    demand: 72,
    current: 78,
    target: 82,
    trend: "up",
    relatedJobs: ["字节跳动", "小红书", "百度"],
    evidence: ["项目采用 App Router", "已处理图表客户端渲染与生产构建"],
    recommendation: "补充 SSR、静态生成、路由组织和部署优化说明。",
    learningPlan: ["整理 App Router 页面分层", "记录 Recharts 客户端挂载处理", "补一个服务端数据加载示例"],
    matchedProjects: ["JobPilot"],
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    category: "framework",
    demand: 64,
    current: 84,
    target: 80,
    trend: "stable",
    relatedJobs: ["美团", "小红书", "快手"],
    evidence: ["已完成后台布局、响应式卡片和表格适配", "统一使用设计变量和组件样式"],
    recommendation: "展示如何控制信息密度、响应式和组件一致性。",
    learningPlan: ["总结移动端看板改造过程", "整理按钮、表格、卡片的样式规范"],
    matchedProjects: ["JobPilot", "Explore"],
  },
  {
    id: "state-management",
    name: "状态管理",
    category: "engineering",
    demand: 78,
    current: 68,
    target: 82,
    trend: "stable",
    relatedJobs: ["美团", "京东", "腾讯"],
    evidence: ["岗位管理和面试看板使用本地状态完成完整闭环", "筛选、弹窗、拖拽阶段更新逻辑可复用"],
    recommendation: "增加 Zustand 或 Redux Toolkit 场景，展示跨页面数据协作。",
    learningPlan: ["把岗位数据抽成 store", "补充状态持久化和撤销操作", "准备状态设计图"],
    matchedProjects: ["JobPilot", "ChatFlow"],
  },
  {
    id: "performance",
    name: "性能优化",
    category: "engineering",
    demand: 82,
    current: 63,
    target: 84,
    trend: "up",
    relatedJobs: ["字节跳动", "滴滴", "快手"],
    evidence: ["已做响应式截图验证和图表稳定渲染", "构建流程已通过生产检查"],
    recommendation: "补齐性能指标、长列表优化、图表渲染策略和 Lighthouse 记录。",
    learningPlan: ["加入虚拟列表或分页性能对比", "记录一次 Lighthouse 优化前后数据", "准备 React memo 与渲染排查案例"],
    matchedProjects: ["JobPilot"],
  },
  {
    id: "testing",
    name: "自动化测试",
    category: "engineering",
    demand: 70,
    current: 58,
    target: 78,
    trend: "up",
    relatedJobs: ["阿里巴巴", "网易", "腾讯"],
    evidence: ["已用浏览器脚本验证关键页面、交互和截图", "覆盖桌面和手机尺寸"],
    recommendation: "补充组件测试、E2E 用例和 CI 运行说明。",
    learningPlan: ["把验证脚本整理成 smoke test", "补 3 条表单校验测试", "接入 GitHub Actions 示例"],
    matchedProjects: ["JobPilot"],
  },
  {
    id: "nodejs",
    name: "Node.js",
    category: "backend",
    demand: 58,
    current: 48,
    target: 70,
    trend: "stable",
    relatedJobs: ["小红书", "百度", "网易"],
    evidence: ["当前项目已有脚本化验证和构建流程", "已接入账号级 API 与文件数据库"],
    recommendation: "增加轻量接口层或 mock server，说明前后端协作能力。",
    learningPlan: ["补一个岗位 CRUD API 设计", "加入 mock service 或 Next route handlers", "整理接口错误处理策略"],
    matchedProjects: ["ChatFlow"],
  },
  {
    id: "cicd",
    name: "CI/CD",
    category: "tooling",
    demand: 62,
    current: 45,
    target: 72,
    trend: "up",
    relatedJobs: ["腾讯", "网易", "滴滴"],
    evidence: ["本地已形成 typecheck、lint、build、browser verify 流程", "已配置 GitHub Actions 自动化流水线"],
    recommendation: "补充自动化检查流水线和部署预览说明。",
    learningPlan: ["新增 GitHub Actions 配置", "沉淀 PR 检查说明", "记录构建失败排查案例"],
    matchedProjects: ["JobPilot"],
  },
  {
    id: "visualization",
    name: "数据可视化",
    category: "framework",
    demand: 66,
    current: 76,
    target: 80,
    trend: "stable",
    relatedJobs: ["百度", "滴滴", "字节跳动"],
    evidence: ["仪表盘已使用折线图、环形图和横向柱状图", "技能分析页展示多维匹配指标"],
    recommendation: "补充图表交互、空状态和大数据量处理说明。",
    learningPlan: ["增加图表 tooltip 业务解释", "补一个异常数据空状态", "整理图表选型说明"],
    matchedProjects: ["JobPilot"],
  },
];

export const projectMatches: ProjectMatch[] = [
  {
    id: "jobpilot",
    name: "JobPilot 求职管理平台",
    description: "覆盖仪表盘、岗位管理、面试看板和技能分析，适合展示完整业务闭环。",
    score: 91,
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Recharts"],
    nextImprovements: ["扩展权限角色", "增加更多 E2E 场景", "接入云数据库与监控"],
  },
  {
    id: "chatflow",
    name: "ChatFlow AI 聊天应用",
    description: "适合补充流式接口、状态管理、多轮会话和服务端协作能力。",
    score: 76,
    skills: ["React", "Node.js", "状态管理", "接口设计"],
    nextImprovements: ["加入消息持久化", "优化流式响应", "补充错误恢复"],
  },
  {
    id: "explore",
    name: "Explore 发现社区",
    description: "适合展示内容列表、移动端体验、筛选推荐和视觉还原能力。",
    score: 68,
    skills: ["Vue", "Tailwind CSS", "移动端适配", "组件拆分"],
    nextImprovements: ["加入列表虚拟化", "补充搜索排序", "优化首屏加载"],
  },
];
